name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # BACKEND
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Test backend
        working-directory: backend
        run: npm test --if-present

      - name: Lint backend
        working-directory: backend
        run: npm run lint --if-present

      # FRONTEND
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Test frontend
        working-directory: frontend
        run: npm test --if-present

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint --if-present
      
      # ===== DOCKER BUILD =====
      - name: Build backend Docker image
        run: |
          docker build \
            -t backend-ci-test \
            -f /home/azureuser/CloudNativeApplicationCurse/backend/Dockerfile \
            /home/azureuser/CloudNativeApplicationCurse

      - name: Build frontend Docker image
        run: |
          docker build \
            -t frontend-ci-test \
            -f /home/azureuser/CloudNativeApplicationCurse/frontend/Dockerfile \
            /home/azureuser/CloudNativeApplicationCurse

